### ISSUE TITLE
Doesn't appear to be working properly per the example instructions?

### ISSUE THREAD

**Issue by brianhall12345** [retejs/minimap-plugin#2]
I tried adding the minimap plugin to the Modules example:
https://codepen.io/Ni55aN/pen/QOEbEW

I used the instructions verbatim first, adding:
```
import MinimapPlugin from 'rete-minimap-plugin';

editor.use(MinimapPlugin);
```

right after the last editor.use() statement (around line 222).
This resulted in nothing rendering.

I then included the js file in the index.html, and removed the import statement above, leaving the editor.use(MinimapPlugin).

This results in a minimap appearing, but the nodes don't render.

Is this not the correct way to use this plugin?

**Comment by Ni55aN** [comment]
> used the instructions verbatim first, adding:

Codepen doesn't support ES modules (same as browser)

> This resulted in nothing rendering.

TypeError occurs, `Vue` in undefined, because Vue.js dependency missed
![screenshot from 2019-02-10 13-21-48](https://user-images.githubusercontent.com/8259641/52533069-00b7af80-2d37-11e9-999a-f5538752f753.png)

You need that two scripts

![opera snapshot_2019-02-10_131943_codepen io](https://user-images.githubusercontent.com/8259641/52533078-35c40200-2d37-11e9-9046-96869b60923e.png)


FYI I recommend to build projects via Webpack (or something else) due to the difficulty in managing dependencies with the old way of including them via `<script>`

**Comment by brianhall12345** [comment]
Thanks! I'll give this a try.  I didn't see anything in the minimap-plugin documentation that mentioned its dependencies.  It would be helpful if all the listed plugins listed their dependencies.

**Comment by Ni55aN** [comment]
all dependencies listed in package.json -> "dependencies"

**Comment by brianhall12345** [comment]
I'll be sure to look there next time. I'm somewhat new to Node.js, so I guess I was expecting to find this kind of information here:
https://rete.js.org/#/docs/plugins/minimap
Perhaps scraping the package.json and providing that information there as well? Just a suggestion. Thanks for the quick feedback.
